### ISSUE TITLE
from read_write_model import Camera, Image as ColmapImage, read_model

### ISSUE THREAD

**Issue by nanasylum** [Two-Shots-Are-Enough/COLMAP2torch#2]
Hi, thank you sooooo much for your work! It saves my life!!!
But i wanna know in file: format_changer.py----line20----from read_write_model import Camera, Image as ColmapImage, read_model
what is that? could you please add the code about this :)

**Comment by yoomimi** [comment]
Oh, thank u for your interest!

I've forgotten some of the codes.. yeah.

`read_write_model` is COLMAP official python code.
[https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py](https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py)
